# Generated by Django 5.0.6 on 2024-05-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombrepro',
            new_name='nombreart',
        ),
    ]
