# Generated by Django 5.0.6 on 2024-05-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0002_rename_nombrepro_producto_nombreart'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='Sin marca', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
