# Generated by Django 5.0.6 on 2024-05-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0004_remove_producto_id_producto_idproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idproducto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
