# Generated by Django 5.0.6 on 2024-05-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0005_alter_producto_idproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idproducto',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
