# Generated by Django 5.0.6 on 2024-06-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0006_alter_producto_idproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idproducto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
